# Generated by Django 3.2.2 on 2021-06-07 13:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_storydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='storydata',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 6, 7, 13, 46, 29, 128550, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
