# Generated by Django 3.2.2 on 2021-07-25 14:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0006_storydata_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='storydata',
            name='likes',
            field=models.ManyToManyField(related_name='storyLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
