# Generated by Django 3.2.2 on 2021-07-26 09:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0007_storydata_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storydata',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='storyLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
